# postgresql servers
- include: dbservers.yml
# elasticsearch servers
- include: esservers.yml
# apache2 web servers
- include: webservers.yml
# ssmtp servers
- include: smtpservers.yml
# archive web servers
- include: archiveservers.yml
